# Generated by Django 2.1 on 2018-09-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreV_0_1', '0002_auto_20180910_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealTitle', models.CharField(max_length=512)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='coreV_0_1.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerId', models.CharField(default='1', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('offerTitle', models.CharField(max_length=512)),
                ('offerUrl', models.URLField(default='http://www.cuelinks.com/', max_length=2048)),
                ('offerTerms', models.TextField(blank=True, null=True)),
                ('coupounCode', models.CharField(blank=True, max_length=30, null=True)),
                ('offerStatus', models.CharField(default='live', max_length=10, null=True)),
                ('offerStartTime', models.DateTimeField()),
                ('offerEndTime', models.DateTimeField()),
                ('offerImageUrl', models.URLField(default='http://www.cuelinks.com/', max_length=2048)),
                ('categoryName', models.CharField(blank=True, max_length=128, null=True)),
                ('storeName', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreV_0_1.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirty_date', models.DateTimeField(null=True)),
                ('catTitle', models.CharField(max_length=512)),
                ('payout', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(blank=True, max_length=64, null=True)),
                ('storeAffName', models.CharField(default='Cuelinks', max_length=128)),
                ('logoUrl', models.URLField(blank=True, max_length=1024, null=True)),
                ('affUrl', models.URLField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payouts', models.TextField(blank=True, null=True)),
                ('categoriesList', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payout',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_payouts', to='coreV_0_1.Store'),
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coreV_0_1.Store'),
        ),
        migrations.AddField(
            model_name='deal',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='coreV_0_1.Store'),
        ),
        migrations.AddField(
            model_name='category',
            name='stores',
            field=models.ManyToManyField(related_name='categories', to='coreV_0_1.Store'),
        ),
    ]
